### ISSUE TITLE
Add location 

### ISSUE THREAD

**Issue by DoaaIkzamia** [MehaRima/online_ambulance_booking_service#5]
Good afternoon @MehaRima , I suggest to add location of the person whose request ambulance in the project

**Comment by MehaRima** [comment]
> Good afternoon @MehaRima , I suggest to add location of the person whose request ambulance in the project

Thank you for your valuable suggestion. I am working on the location tracking and similar features.Keep supporting and encouraging. Stay tuned for updates. Warm regards
Saheli Basu
