### ISSUE TITLE
Car Listing page is not working please help as soon as possible. Thanks!

### ISSUE THREAD

**Issue by ghost** [MehaRima/online_ambulance_booking_service#8]
![Capturesss](https://user-images.githubusercontent.com/78077066/106350404-30cd3400-62fb-11eb-9631-7d62405d09ec.PNG)

**Comment by MehaRima** [comment]
Hello, Thanks for your interest in the project.
Please visit this article:-
https://github.com/MehaRima/WebApplication/blob/master/REAME.md
And let me know whether the issue is resolved.
